using System;
using System.Collections.Generic;
using System.Xml;

namespace KK_Plugins {
    class LangCNDic
    {
        public static BepInEx.Logging.ManualLogSource Logger;

        private const string Statement = "本插件由PopChicken@ZOD汉化，若有修改意愿请前往Github clone";

        protected static Dictionary<string, string> En2CnDic = new Dictionary<string, string>()
        {
            //程序字典
            {"open image", "打开图片"},
            {"material editor", "材质编辑器"},
            {"renderer", "渲染器"},
            {"enabled", "启用"},
            {"shadowcastingmode", "阴影投射(ShadowCastingMode)"},
            {"renderqueue", "渲染队列(RenderQueue)"},
            {"twosided", "两侧"},
            {"shadowsonly", "仅阴影"},
            {"receiveshadows", "接收阴影(ReceiveShadows)"},
            {"material", "材质"},
            {"shader", "着色器"},
            {"reset", "重置"},
            {"import texture", "导入纹理"},
            {"export texture", "导出纹理"},
            {"shaderrenderqueue", "着色器渲染队列(ShaderRenderQueue)"},
            {"r", "R"},
            {"g", "G"},
            {"b", "B"},
            {"a", "A"},
            {"no texture", "无纹理"},
            {"offset x", "X偏移(Offset X)"},
            {"y", "Y"},
            {"scale x", "X坐标(Scale X)"},
            {"on", "打开"},
            {"off", "关闭"},
            {"open material editor", "打开材质编辑器"},
            {"open material editor (body)", "打开材质编辑器(身体)"},
            {"open material editor (face)", "打开材质编辑器(脸部)"},
            {"open material editor (all)", "打开材质编辑器(整体)"},
            {"open material editor (back)", "打开材质编辑器(后发)"},
            {"open material editor (front)", "打开材质编辑器(前发)"},
            {"open material editor (side)", "打开材质编辑器(侧发)"},
            {"open material editor (extension)", "打开材质编辑器(接发)"},
            {"open material editor (top)", "打开材质编辑器(上衣)"},
            {"open material editor (bottom)", "打开材质编辑器(下衣)"},
            {"open material editor (bra)", "打开材质编辑器(胸衣)"},
            {"open material editor (underwear)", "打开材质编辑器(胖次)"},
            {"open material editor (gloves)", "打开材质编辑器(手套)"},
            {"open material editor (pantyhose)", "打开材质编辑器(裤袜)"},
            {"open material editor (socks)", "打开材质编辑器(袜子)"},
            {"open material editor (shoes)", "打开材质编辑器(鞋子)"},
            {"export uv map", "导出UV贴图映射(Export UV Map)"},
            {"export .obj", "导出.obj文件"},
            {"ui scale", "UI放大"},
            {"ui height", "UI高度"},
            {"ui width", "UI宽度"},
            {"config", "配置"},

            //Xml字典
            {"animationmask", "动画遮罩"},
            {"alphamask", "Alpha遮罩"},
            {"anotherramp", "另一漫反射(AnoterRamp)"},
            {"bumpmap", "凹凸贴图"},
            {"colormask", "颜色遮罩"},
            {"detailmask", "细节遮罩"},
            {"emissionmap", "自发光贴图"},
            {"glassramp", "玻璃漫反射"},
            {"hairgloss", "头发光泽"},
            {"linemask", "线性遮罩"},
            {"liquidmask", "液体遮罩(LiquidMask)"},
            {"maintex", "主材质"},
            {"metallicglossmap", "金属光泽贴图"},
            {"normalmap", "一般贴图"},
            {"parallaxmap", "视差贴图"},
            {"patternmask1", "图案遮罩1"},
            {"patternmask2", "图案遮罩2"},
            {"patternmask3", "图案遮罩3"},
            {"texcoord", "纹理坐标"},
            {"texture1", "纹理1"},
            {"texture2", "纹理2"},
            {"texture3", "纹理3"},
            {"texture4", "纹理4"},
            {"texturesample0", "纹理样本0"},
            {"clock", "时钟颜色"},
            {"color", "颜色"},
            {"color1_2", "颜色1_2"},
            {"color2", "颜色2"},
            {"color2_2", "颜色2_2"},
            {"color3", "颜色3"},
            {"color3_2", "颜色3_2"},
            {"color4", "颜色4"},
            {"color_4", "颜色_4"},
            {"color5", "颜色_5"},
            {"emission", "自发光颜色"},
            {"eyebaseoffset", "眼部基础偏移"},
            {"line", "线条"},
            {"linecolor", "线条颜色"},
            {"liquidtiling", "液态平铺"},
            {"maincolor", "主颜色"},
            {"patternuv1", "图案UV1"},
            {"patternuv2", "图案UV2"},
            {"patternuv3", "图案UV3"},
            {"overcolor1", "覆盖色1(OverColor1)"},
            {"overcolor2", "覆盖色2"},
            {"overcolor3", "覆盖色3"},
            {"shadow", "阴影"},
            {"spec", "镜面颜色(Spec)"},
            {"specular", "镜面颜色(Specular)"},
            {"specularcolor", "镜面颜色(SpecularColor)"},
            {"paint1", "颜料1(paint1)"},
            {"refcolor", "颜色值(refcolor)"},
            {"shadowcolor", "阴影颜色"},
            {"texture2uv", "纹理2UV"},
            {"texture3uv", "纹理3UV"},
            {"texture4uv", "纹理4UV"},
            {"_dirty", "脏度(_dirty)"},
            {"alpha", ""},
            {"alpha_a", ""},
            {"alpha_b", ""},
            {"ambientshadowoff", "环境阴影OFF"},
            {"anotherrampfull", ""},
            {"blendnormalmapscale", ""},
            {"bumpscale", "凹凸程度"},
            {"colorinverse", ""},
            {"colorsort", "颜色排序"},
            {"cutoff", ""},
            {"cutoutclip", ""},
            {"detailblineg", ""},
            {"detailblinega", ""},
            {"detailnormalmapscale", "一般细节贴图强度"},
            {"detailnormalmapscale2", "一般细节贴图强度2"},
            {"detailrliner", ""},
            {"dstblend", ""},
            {"emissionpower", "自发光功率"},
            {"glossmapscale", "光滑贴图强度"},
            {"glossiness", "反光度"},
            {"glossyreflections", "镜面反射"},
            {"haireffect", "发丝效果"},
            {"hairlength2", "头发长度"},
            {"lightcancel", "光线吸收"},
            {"linetexon", ""},
            {"linewidths", "线条宽度S"},
            {"linewidth", "线条宽度"},
            {"liquidbbot", ""},
            {"liquidbtop", ""},
            {"liquidface", ""},
            {"liquidfbot", ""},
            {"liquidftop", ""},
            {"metallic", "金属感"},
            {"mode", "模式"},
            {"nip", ""},
            {"nipsize", "nip大小"},
            {"nip_specular", "nip反光"},
            {"node_6948", "节点_6948"},
            {"notusetexspecular", "不使用纹理反光"},
            {"occlusionstrength", "吸收强度"},
            {"outline", ""},
            {"parallax", "视差"},
            {"patternclamp1", "图案固定1"},
            {"patternclamp2", "图案固定2"},
            {"patternclamp3", "图案固定3"},
            {"patternrotator1", "图案旋转1"},
            {"patternrotator2", "图案旋转2"},
            {"patternrotator3", "图案旋转3"},
            {"refpower", ""},
            {"rimpower", "边缘高光"},
            {"rimv", "边缘V"},
            {"selectemissionmask", "选择自发光遮罩"},
            {"selectemissionmap", "选择自发光贴图"},
            {"shadowextend", "阴影延展"},
            {"shadowextendanother", "阴影延展(另外)"},
            {"shininess", "光泽度"},
            {"smoothness", "光滑度"},
            {"smoothnesstexturechannel", ""},
            {"speclarheight", "镜面高度"},
            {"speclarpallaxu", "镜面PallaxU"},
            {"speclarpallaxv", "镜面PallaxV"},
            {"speclarshadowheight", "镜面阴影高度"},
            {"speclarswitch", "镜面阴影开关"},
            {"specularhighlights", "镜面高光"},
            {"specularheight", "镜面高度"},
            {"specularpower", "镜面强度"},
            {"specularpowernail", "镜面强度Nail"},
            {"srcblend", ""},
            {"tex1mask", "纹理1遮罩"},
            {"texture4rotator", "纹理4旋转"},
            {"translucency", "透明度"},
            {"transnormaldistortion", "一般透明扭曲"},
            {"transscattering", "透明碎片化"},
            {"transdirect", "透明导向"},
            {"transambient", "透明环境"},
            {"transshadow", "透明阴影"},
            {"upanner", ""},
            {"uvsec", ""},
            {"vpanner", ""},
            {"zwrite", ""},
            {"ditherswitch", "抖动算法"},
            {"yabureditherswitch", "Yabure抖动算法"},
            {"vertexcolor", "顶点颜色"},
            {"emissionrim", "自发光边缘"},
            {"emissioncolortexbase", ""},
            {"float0", ""},
            {"exgloss", "光泽Ex"},
            {"occulusionstrength", "吸收强度"},
            {"emissionstrength", "自发光强度"},
            {"alphaex", ""},
            {"carvaturestrength", "感光强度"},
            {"detailmetallicscale", "细节金属感强度"},
            {"detailmetallicscale2", "细节金属感强度2"},
            {"detailglossscale", "细节光滑度"},
            {"detailglossscale2", "细节光滑度2"},
            {"detailocculusionscale", "细节吸收强度"},
            {"detailocculusionscale2", "细节吸收强度2"},
            {"detailuvrotator", "细节UV旋转"},
            {"detailuv2rotator", "细节UV2旋转"},
            {"transmissionstrength", "传递强度"},
            {"weatheringall", "整体不知名液体"},
            {"weatheringrange1", "不知名液体范围1"},
            {"weatheringrange2", "不知名液体范围2"},
            {"weatheringrange3", "不知名液体范围3"},
            {"weatheringrange4", "不知名液体范围4"},
            {"weatheringrange5", "不知名液体范围5"},
            {"weatheringrange6", "不知名液体范围6"},
            {"uvscalepattern", "UV强度图案"},
            {"basecolor", "基础颜色"},
            {"emissioncolor", "自发光颜色"},
            {"detailuv", "细节UV"},
            {"detailuv2", "细节UV2"},
            {"weatheringuv", "不知名液体UV"},
            {"occlusionmap", "吸收贴图(OcclusionMap)"},
            {"detailglossmap", "光泽细节贴图"},
            {"detailglossmap2", "光泽细节贴图2"},
            {"detailmaintex", "主要细节贴图"},
            {"weatheringmap", "不知名液体贴图"},
            {"weatheringmask", "不知名液体遮罩"},
            {"patternuv1rotator", "图案UV1旋转"},
            {"patternuv2rotator", "图案UV2旋转"},
            {"patternuv3rotator", "图案UV3旋转"},
            {"metallic2", "金属感2"},
            {"metallic3", "金属感3"},
            {"metallic4", "金属感4"},
            {"glossiness2", "反光度2"},
            {"glossiness3", "反光度3"},
            {"glossiness4", "反光度4"},
            {"vertexcolormask", ""},
            {"topgradation", "顶层次"},
            {"undergradation", "底层次"},
            {"detailscale", "细节强度"},
            {"highlight", "高光"},
            {"undercolor", "下方颜色(UnderColor)"},
            {"occlusion", "吸收"},
            {"fresnelscale", "菲涅尔反射强度"},
            {"bitangentrim", ""},
            {"matcaptilling", ""},
            {"matcapscale", "Matcap强度"},
            {"gloss", "光泽"},
            {"detailmainscale", "主要细节强度"},
            {"bumpscale2", "凹凸强度2"},
            {"riality", ""},
            {"nipgloss", "nip光泽"},
            {"nailgloss", "指甲光泽"},
            {"nipscale", ""},
            {"texture3rotator", "纹理3旋转"},
            {"texture4scale", "纹理4强度"},
            {"color13", "颜色13"},
            {"matcaptexture", "Matcap纹理"},
            {"hairbase", "头发基底(HairBase)"},
            {"bumpmap2", "凹凸贴图2"},
            {"texcoord2", "纹理坐标2"},
            {"texcoord3", "纹理坐标3"},
            {"emissive", "自发光"},
            {"uvpannertime", "UV偏移器时间"},
            {"uvpannerspeedy", "UV偏移器y坐标速率"},
            {"uvpannerspeedx", "UV偏移器x坐标速率"},
            {"vector0", "向量0(Vector0)"},
            {"timemask", "时间遮罩(TimeMask)"},
            {"float1", "浮点数1"},
            {"emissionmaincolorbase", "自发光主颜色基底"},
            {"detailalbedomapscale", ""},
            {"detailalbedonormalscale", ""},
            {"uv", ""},
            {"emissonmap", "自发光贴图"},
            {"detailnormalmap", "一般细节贴图"},
            {"detailalbedomap", ""},
        };

        public static void Init()
        {
            XmlReader reader;
        }

        public static string Trans2CN(string s)
        {
            if (s.IsNullOrEmpty()) return "";

            //Logger.LogInfo($"[{MaterialEditor.PluginNameInternal}]尝试翻译\"{s}\"");
            int pos = s.IndexOf(':');

            if (pos == -1) pos = s.Length;
            string _s = s.Substring(0, pos);

            if (En2CnDic.ContainsKey(_s.ToLower()) && En2CnDic[_s.ToLower()].Length > 0) {
                //Logger.LogInfo($"[{MaterialEditor.PluginNameInternal}]找到片段\"{_s}\"的对应翻译\"{En2CnDic[_s.ToLower()]}\"");
                return En2CnDic[_s.ToLower()] + s.Substring(pos);
            }
            else {
                //Logger.LogInfo($"[{MaterialEditor.PluginNameInternal}]未找到片段\"{_s}\"的对应翻译" );
                return s;
            }
        }
    }
}

// rend.NameFormatted()
// materialName
// shaderName
// LabelText(ColorDefault())
// LabelText(defaultValue)
//  labelOffsetScaleText()
//  LabelText(FloatDefault())